# Generated by Django 3.0.8 on 2020-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_auto_20201012_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorporatesTalks',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
