# Generated by Django 3.0.8 on 2020-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_auto_20201103_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
