# Generated by Django 3.0.8 on 2020-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_course_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
