# Generated by Django 3.0.8 on 2020-11-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_auto_20201120_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='reply',
            new_name='replay',
        ),
    ]
