# Generated by Django 3.0.8 on 2020-11-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LandingPage', '0004_auto_20201103_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatesTalks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('organization', models.CharField(max_length=250)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_course', to='LandingPage.Course')),
            ],
            options={
                'verbose_name': 'Corporate Talks',
                'verbose_name_plural': 'Corporate Talks',
            },
        ),
    ]
