# Generated by Django 3.0.8 on 2020-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatestalks',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatestalks',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
