# Generated by Django 3.0.8 on 2020-11-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0003_auto_20201118_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitatorqueries',
            name='status',
        ),
        migrations.AddField(
            model_name='facilitatorqueries',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorqueries',
            name='replay',
            field=models.CharField(default='Doubt', max_length=250),
        ),
        migrations.AddField(
            model_name='facilitatorqueries',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
