# Generated by Django 3.0.8 on 2020-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0004_auto_20201128_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorqueries',
            name='replay',
            field=models.CharField(max_length=250),
        ),
    ]
