# Generated by Django 3.0.8 on 2020-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='blob',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
