# Generated by Django 3.0.8 on 2020-11-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus Talks',
            },
        ),
    ]
