# Generated by Django 3.0.8 on 2020-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='mobile',
        ),
        migrations.AddField(
            model_name='campus',
            name='campus',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
