# Generated by Django 3.0.8 on 2020-11-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_auto_20201103_1935'),
        ('campus', '0002_auto_20201105_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='course_name',
        ),
        migrations.AddField(
            model_name='campus',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_course', to='LandingPage.Course'),
        ),
    ]
