# Generated by Django 3.0.8 on 2020-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20201105_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
