# Generated by Django 3.0.8 on 2020-10-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_auto_20201029_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
