# Generated by Django 3.0.8 on 2020-11-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_lqueries_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lqueries',
            old_name='reply',
            new_name='replay',
        ),
    ]
