# Generated by Django 3.0.8 on 2020-12-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_auto_20201129_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_revenue', models.FloatField(null=True)),
                ('facilitator_revenue', models.FloatField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('revenue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='payment_gateway.OrderCourses')),
            ],
        ),
    ]
