# Generated by Django 3.0.8 on 2020-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=100, null=True),
        ),
    ]
