# Generated by Django 3.0.8 on 2020-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0005_revenue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='admin_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='facilitator_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
