# Generated by Django 3.1.4 on 2020-12-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0006_auto_20201201_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=250, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_order', to='payment_gateway.order')),
            ],
        ),
    ]
