# Generated by Django 3.1.4 on 2020-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0007_razorpaydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaydetails',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='razorpaydetails',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
