# Generated by Django 3.1.4 on 2020-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0009_auto_20201203_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorsubscriptions',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorsubscriptions',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
